name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd courses && npm install
      - name: Install slidev
        run:  cd courses && npm i -g @slidev/cli
      - name: Install for PDF
        run: cd courses && npm i -D playwright-chromium
      - name: Build
        run: cd courses && slidev build --base ./ # Change this line
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: courses/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}